### ISSUE TITLE
Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by philkunz** [Daplie/le-acme-core#15]
So I'm trying to get this working after letsencrypt failed silently for me and I wanted a little more control.

However this:
```javascript
                let options = {
                    newRegUrl: this.acmeUrls.newReg,
                    email: 'domains@lossless.org', // valid email (server checks MX records)
                    accountKeypair: { // privateKeyPem or privateKeyJwt 
                        privateKeyPem: this.keyPair
                    },
                    agreeToTerms: function (tosUrl, done) {
                        done(null, tosUrl)
                    }
                }
                ACME.registerNewAccount(options, (err, regr) => {
                    if(err) {
                        console.log(err)
                        // done.reject(err)
                    }
                    // done.resolve(regr)
                })
```
fails for me with 
```
Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
      at fromObject (buffer.js:284:9)
      at Function.Buffer.from (buffer.js:116:10)
      at new Buffer (buffer.js:95:17)
      at decodeString (node_modules/ursa/lib/ursa.js:201:12)
      at Object.createPrivateKey (node_modules/ursa/lib/ursa.js:433:11)
      at Object._ursaImportPem (node_modules/rsa-compat/lib/rsa-ursa.js:60:28)
      at Object.import (node_modules/rsa-compat/lib/rsa-ursa.js:108:11)
      at RSA.signJws.RSA.generateJws.RSA.generateSignatureJws.RSA.generateSignatureJwk (node_modules/rsa-compat/node.js:162:35)
      at Acme.post (node_modules/le-acme-core/lib/acme-client.js:65:9)
      at node_modules/le-acme-core/lib/acme-client.js:58:14
```

any clue why? Keypair is generated with rsa-compat

**Comment by philkunz** [comment]
full code snippet here: https://gitlab.com/pushrocks/smartacme/blob/master/ts/smartacme.classes.smartacme.ts

**Comment by coolaj86** [comment]
I think you'd just want `accountKeypair: this.keyPair`

**Comment by coolaj86** [comment]
I'll take the silence as that must have fixed it (or it didn't matter by the time I replied). Closing.
